version: '3.8'

services:
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - todo-app

  api:
    build:
      context: ./server
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file:
      - ./server/.env
    environment:
      - NODE_ENV=development
    ports:
      - "4000:4000"
    volumes:
      - ./server:/app
      - /app/node_modules
    networks:
      - todo-app
    depends_on:
      - mongo

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "5173:5173"
    volumes:
      - ./client:/app
      - /app/node_modules
    networks:
      - todo-app
    environment:
      - VITE_API_URL=http://localhost:4000
    command: npm run dev -- --host
    depends_on:
      - api

volumes:
  mongo_data:

networks:
  todo-app:
    driver: bridge