version: '3.8'

services:
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - todo-app

  api:
    build:
      context: ./server
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file:
      - ./server/.env
    environment:
      - NODE_ENV=development
    ports:
      - "4000:4000"
    volumes:
      - ./server:/app
      - /app/node_modules
    networks:
      - todo-app
    depends_on:
      - mongo

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "5173:5173"
    env_file:
      - ./client/.env
    environment:
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ./client:/app
      - /app/node_modules
      - /app/public
    networks:
      - todo-app
    command: npm run dev -- --host 0.0.0.0 --port 5173
    depends_on:
      - api

volumes:
  mongo_data:

networks:
  todo-app:
    driver: bridge